// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yabzmahzobwuwxylcwoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhYnptYWh6b2J3dXd4eWxjd295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzE0NjcsImV4cCI6MjA3MjgwNzQ2N30.6e8_AHtks0vPIwp-eZlnsWDpQnHUssDAKDy6QzEvL0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});